#[derive(Copy, Clone, Debug, Default, PartialEq)]
pub struct ServingSloMissPenaltyWeights {
    pub aggregate: f64,
    pub ttft: f64,
    pub tpot: f64,
    pub itl: f64,
    pub e2el: f64,
    pub deadline: f64,
}

impl ServingSloMissPenaltyWeights {
    pub fn from_aggregate(aggregate: f64) -> Self {
        Self {
            aggregate,
            ..Self::default()
        }
    }

    pub fn any_nonzero(self) -> bool {
        self.aggregate > 0.0
            || self.ttft > 0.0
            || self.tpot > 0.0
            || self.itl > 0.0
            || self.e2el > 0.0
            || self.deadline > 0.0
    }
}

#[derive(Copy, Clone, Debug, Default, PartialEq)]
pub struct ServingSloMissPenaltyComponents {
    pub ttft: f64,
    pub tpot: f64,
    pub itl: f64,
    pub e2el: f64,
    pub deadline: f64,
    pub total: f64,
}

impl ServingSloMissPenaltyComponents {
    pub(in crate::serving) fn add_assign(&mut self, other: Self) {
        self.ttft += other.ttft;
        self.tpot += other.tpot;
        self.itl += other.itl;
        self.e2el += other.e2el;
        self.deadline += other.deadline;
        self.total += other.total;
    }
}

#[derive(Copy, Clone, Debug, PartialEq)]
pub struct ServingMetrics {
    pub ttft_s: f64,
    pub ttft_p50_s: f64,
    pub ttft_p90_s: f64,
    pub ttft_p95_s: f64,
    pub ttft_p99_s: f64,
    pub ttft_max_s: f64,
    pub ttft_slo_constrained_requests: u32,
    pub ttft_slo_missed_requests: u32,
    pub ttft_slo_miss_rate: f64,
    pub tpot_s: f64,
    pub tpot_p50_s: f64,
    pub tpot_p90_s: f64,
    pub tpot_p95_s: f64,
    pub tpot_p99_s: f64,
    pub tpot_max_s: f64,
    pub tpot_slo_constrained_requests: u32,
    pub tpot_slo_missed_requests: u32,
    pub tpot_slo_miss_rate: f64,
    pub itl_s: f64,
    pub itl_p50_s: f64,
    pub itl_p90_s: f64,
    pub itl_p95_s: f64,
    pub itl_p99_s: f64,
    pub itl_max_s: f64,
    pub itl_slo_constrained_requests: u32,
    pub itl_slo_missed_requests: u32,
    pub itl_slo_miss_rate: f64,
    pub decode_iterations: u64,
    pub decode_iteration_s: f64,
    pub decode_iteration_p50_s: f64,
    pub decode_iteration_p90_s: f64,
    pub decode_iteration_p95_s: f64,
    pub decode_iteration_p99_s: f64,
    pub decode_iteration_max_s: f64,
    pub throughput_tokens_per_s: f64,
    pub e2el_s: f64,
    pub e2el_p50_s: f64,
    pub e2el_p90_s: f64,
    pub e2el_p95_s: f64,
    pub e2el_p99_s: f64,
    pub e2el_max_s: f64,
    pub e2el_slo_constrained_requests: u32,
    pub e2el_slo_missed_requests: u32,
    pub e2el_slo_miss_rate: f64,
    pub deadline_miss_rate: f64,
    pub service_s: f64,
    pub prefill_s: f64,
    pub prefill_chunks: u64,
    pub prompt_tokens: u64,
    pub prefix_cache_hit_tokens: u64,
    pub effective_prefill_tokens: u64,
    pub prefix_cache_hit_rate: f64,
    pub kv_transfer_s: f64,
    pub kv_queue_s: f64,
    pub kv_worker_queue_s: f64,
    pub kv_resource_queue_s: f64,
    pub decode_queue_s: f64,
    pub prefill_worker_queue_s: f64,
    pub prefill_resource_queue_s: f64,
    pub decode_worker_queue_s: f64,
    pub decode_resource_queue_s: f64,
    pub decode_s: f64,
    pub queue_delay_s: f64,
    pub queue_delay_p90_s: f64,
    pub queue_delay_p95_s: f64,
    pub queue_delay_max_s: f64,
    pub peak_prefill_tokens: u64,
    pub peak_prefill_tokens_per_node: u64,
    pub peak_prefill_tokens_per_gpu: u64,
    pub peak_decode_sequences: u32,
    pub peak_resident_tokens: u64,
    pub peak_decode_sequences_per_node: u32,
    pub peak_resident_tokens_per_node: u64,
    pub peak_decode_sequences_per_gpu: u32,
    pub peak_resident_tokens_per_gpu: u64,
    pub peak_kv_blocks: u64,
    pub peak_allocated_kv_tokens: u64,
    pub peak_kv_fragmentation_tokens: u64,
    pub peak_kv_block_table_bytes: u64,
    pub peak_kv_blocks_per_node: u64,
    pub peak_allocated_kv_tokens_per_node: u64,
    pub peak_kv_fragmentation_tokens_per_node: u64,
    pub peak_kv_block_table_bytes_per_node: u64,
    pub peak_kv_blocks_per_gpu: u64,
    pub peak_allocated_kv_tokens_per_gpu: u64,
    pub peak_kv_fragmentation_tokens_per_gpu: u64,
    pub peak_kv_block_table_bytes_per_gpu: u64,
    pub decode_sequence_utilization: f64,
    pub resident_token_utilization: f64,
    pub kv_block_utilization: f64,
    pub decode_sequence_per_node_utilization: f64,
    pub resident_token_per_node_utilization: f64,
    pub kv_block_per_node_utilization: f64,
    pub decode_sequence_per_gpu_utilization: f64,
    pub resident_token_per_gpu_utilization: f64,
    pub kv_block_per_gpu_utilization: f64,
    pub scheduled_makespan_s: f64,
    pub scheduled_requests: u32,
    pub admitted_requests: u32,
    pub completed_requests: u32,
    pub rejected_requests: u32,
    pub timed_out_requests: u32,
    pub cancelled_requests: u32,
    pub deadline_constrained_requests: u32,
    pub deadline_missed_requests: u32,
    pub measured_requests: u32,
    pub measurement_start_s: f64,
    pub measurement_end_s: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ServingMetricBreakdown {
    pub group: String,
    pub key: String,
    pub request_count: u32,
    pub completed_requests: u32,
    pub failed_requests: u32,
    pub rejected_requests: u32,
    pub timed_out_requests: u32,
    pub cancelled_requests: u32,
    pub output_tokens: u64,
    pub lifecycle_event_metric_request_count: u32,
    pub fallback_metric_request_count: u32,
    pub metric_source_counts: Vec<ServingMeasurementMetricSourceCount>,
    pub deadline_constrained_requests: u32,
    pub deadline_missed_requests: u32,
    pub deadline_miss_rate: f64,
    pub ttft_slo_constrained_requests: u32,
    pub ttft_slo_missed_requests: u32,
    pub ttft_slo_miss_rate: f64,
    pub tpot_slo_constrained_requests: u32,
    pub tpot_slo_missed_requests: u32,
    pub tpot_slo_miss_rate: f64,
    pub itl_slo_constrained_requests: u32,
    pub itl_slo_missed_requests: u32,
    pub itl_slo_miss_rate: f64,
    pub e2el_slo_constrained_requests: u32,
    pub e2el_slo_missed_requests: u32,
    pub e2el_slo_miss_rate: f64,
    pub ttft_s: f64,
    pub ttft_p90_s: f64,
    pub ttft_p95_s: f64,
    pub ttft_max_s: f64,
    pub tpot_s: f64,
    pub tpot_p90_s: f64,
    pub tpot_p95_s: f64,
    pub tpot_max_s: f64,
    pub itl_s: f64,
    pub itl_p90_s: f64,
    pub itl_p95_s: f64,
    pub itl_max_s: f64,
    pub throughput_tokens_per_s: f64,
    pub e2el_s: f64,
    pub e2el_p90_s: f64,
    pub e2el_p95_s: f64,
    pub e2el_max_s: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ServingSteadyStateMetricObservation {
    pub metric: String,
    pub unit: String,
    pub sample_count: u32,
    pub mean: f64,
    pub stddev: f64,
    pub cv: f64,
    pub std_error: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ServingSteadyStateUtilizationObservation {
    pub source: String,
    pub phase: String,
    pub resource_kind: String,
    pub resource: String,
    pub bucket_count: u32,
    pub active_bucket_count: u32,
    pub event_count: u32,
    pub mean_utilization: f64,
    pub max_utilization: f64,
    pub utilization_cv: f64,
}

#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct ServingMeasurementMetricSourceCount {
    pub metric_source: String,
    pub request_count: u32,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ServingMeasurementWindowObservation {
    pub source: String,
    pub start_s: f64,
    pub end_s: f64,
    pub duration_s: f64,
    pub request_count: u32,
    pub completed_request_count: u32,
    pub failed_request_count: u32,
    pub rejected_request_count: u32,
    pub timed_out_request_count: u32,
    pub cancelled_request_count: u32,
    pub deadline_constrained_request_count: u32,
    pub deadline_missed_request_count: u32,
    pub measured_requests: u32,
    pub lifecycle_event_metric_request_count: u32,
    pub fallback_metric_request_count: u32,
    pub metric_source_counts: Vec<ServingMeasurementMetricSourceCount>,
    pub configured_start_bound: bool,
    pub configured_end_bound: bool,
    pub steady_state_requested: bool,
    pub steady_state_applied: bool,
    pub steady_state_candidate_start_s: Option<f64>,
    pub steady_state_candidate_end_s: Option<f64>,
    pub steady_state_min_requests: Option<u32>,
    pub steady_state_max_cv: Option<f64>,
    pub steady_state_sample_count: u32,
    pub steady_state_matching_window_count: u32,
    pub steady_state_candidate_request_count: Option<u32>,
    pub steady_state_candidate_e2el_mean_s: Option<f64>,
    pub steady_state_candidate_e2el_stddev_s: Option<f64>,
    pub steady_state_candidate_e2el_cv: Option<f64>,
    pub steady_state_candidate_e2el_std_error_s: Option<f64>,
    pub steady_state_candidate_metric_count: u32,
    pub steady_state_candidate_worst_metric: Option<String>,
    pub steady_state_candidate_worst_cv: Option<f64>,
    pub steady_state_candidate_output_tokens: Option<u64>,
    pub steady_state_candidate_throughput_tokens_per_s: Option<f64>,
    pub steady_state_candidate_metrics: Vec<ServingSteadyStateMetricObservation>,
    pub steady_state_candidate_utilization_count: u32,
    pub steady_state_candidate_worst_utilization_resource: Option<String>,
    pub steady_state_candidate_worst_utilization_cv: Option<f64>,
    pub steady_state_candidate_utilization: Vec<ServingSteadyStateUtilizationObservation>,
}

impl ServingMeasurementWindowObservation {
    pub(in crate::serving) fn rejected() -> Self {
        Self {
            source: "unavailable".to_string(),
            start_s: f64::INFINITY,
            end_s: f64::INFINITY,
            duration_s: f64::INFINITY,
            request_count: 0,
            completed_request_count: 0,
            failed_request_count: 0,
            rejected_request_count: 0,
            timed_out_request_count: 0,
            cancelled_request_count: 0,
            deadline_constrained_request_count: 0,
            deadline_missed_request_count: 0,
            measured_requests: 0,
            lifecycle_event_metric_request_count: 0,
            fallback_metric_request_count: 0,
            metric_source_counts: Vec::new(),
            configured_start_bound: false,
            configured_end_bound: false,
            steady_state_requested: false,
            steady_state_applied: false,
            steady_state_candidate_start_s: None,
            steady_state_candidate_end_s: None,
            steady_state_min_requests: None,
            steady_state_max_cv: None,
            steady_state_sample_count: 0,
            steady_state_matching_window_count: 0,
            steady_state_candidate_request_count: None,
            steady_state_candidate_e2el_mean_s: None,
            steady_state_candidate_e2el_stddev_s: None,
            steady_state_candidate_e2el_cv: None,
            steady_state_candidate_e2el_std_error_s: None,
            steady_state_candidate_metric_count: 0,
            steady_state_candidate_worst_metric: None,
            steady_state_candidate_worst_cv: None,
            steady_state_candidate_output_tokens: None,
            steady_state_candidate_throughput_tokens_per_s: None,
            steady_state_candidate_metrics: Vec::new(),
            steady_state_candidate_utilization_count: 0,
            steady_state_candidate_worst_utilization_resource: None,
            steady_state_candidate_worst_utilization_cv: None,
            steady_state_candidate_utilization: Vec::new(),
        }
    }
}

impl ServingMetrics {
    pub(in crate::serving) fn rejected() -> Self {
        Self {
            ttft_s: f64::INFINITY,
            ttft_p50_s: f64::INFINITY,
            ttft_p90_s: f64::INFINITY,
            ttft_p95_s: f64::INFINITY,
            ttft_p99_s: f64::INFINITY,
            ttft_max_s: f64::INFINITY,
            ttft_slo_constrained_requests: 0,
            ttft_slo_missed_requests: 0,
            ttft_slo_miss_rate: f64::INFINITY,
            tpot_s: f64::INFINITY,
            tpot_p50_s: f64::INFINITY,
            tpot_p90_s: f64::INFINITY,
            tpot_p95_s: f64::INFINITY,
            tpot_p99_s: f64::INFINITY,
            tpot_max_s: f64::INFINITY,
            tpot_slo_constrained_requests: 0,
            tpot_slo_missed_requests: 0,
            tpot_slo_miss_rate: f64::INFINITY,
            itl_s: f64::INFINITY,
            itl_p50_s: f64::INFINITY,
            itl_p90_s: f64::INFINITY,
            itl_p95_s: f64::INFINITY,
            itl_p99_s: f64::INFINITY,
            itl_max_s: f64::INFINITY,
            itl_slo_constrained_requests: 0,
            itl_slo_missed_requests: 0,
            itl_slo_miss_rate: f64::INFINITY,
            decode_iterations: 0,
            decode_iteration_s: f64::INFINITY,
            decode_iteration_p50_s: f64::INFINITY,
            decode_iteration_p90_s: f64::INFINITY,
            decode_iteration_p95_s: f64::INFINITY,
            decode_iteration_p99_s: f64::INFINITY,
            decode_iteration_max_s: f64::INFINITY,
            throughput_tokens_per_s: 0.0,
            e2el_s: f64::INFINITY,
            e2el_p50_s: f64::INFINITY,
            e2el_p90_s: f64::INFINITY,
            e2el_p95_s: f64::INFINITY,
            e2el_p99_s: f64::INFINITY,
            e2el_max_s: f64::INFINITY,
            e2el_slo_constrained_requests: 0,
            e2el_slo_missed_requests: 0,
            e2el_slo_miss_rate: f64::INFINITY,
            deadline_miss_rate: f64::INFINITY,
            service_s: f64::INFINITY,
            prefill_s: f64::INFINITY,
            prefill_chunks: 0,
            prompt_tokens: 0,
            prefix_cache_hit_tokens: 0,
            effective_prefill_tokens: 0,
            prefix_cache_hit_rate: 0.0,
            kv_transfer_s: 0.0,
            kv_queue_s: f64::INFINITY,
            kv_worker_queue_s: f64::INFINITY,
            kv_resource_queue_s: f64::INFINITY,
            decode_queue_s: f64::INFINITY,
            prefill_worker_queue_s: f64::INFINITY,
            prefill_resource_queue_s: f64::INFINITY,
            decode_worker_queue_s: f64::INFINITY,
            decode_resource_queue_s: f64::INFINITY,
            decode_s: f64::INFINITY,
            queue_delay_s: f64::INFINITY,
            queue_delay_p90_s: f64::INFINITY,
            queue_delay_p95_s: f64::INFINITY,
            queue_delay_max_s: f64::INFINITY,
            peak_prefill_tokens: 0,
            peak_prefill_tokens_per_node: 0,
            peak_prefill_tokens_per_gpu: 0,
            peak_decode_sequences: 0,
            peak_resident_tokens: 0,
            peak_decode_sequences_per_node: 0,
            peak_resident_tokens_per_node: 0,
            peak_decode_sequences_per_gpu: 0,
            peak_resident_tokens_per_gpu: 0,
            peak_kv_blocks: 0,
            peak_allocated_kv_tokens: 0,
            peak_kv_fragmentation_tokens: 0,
            peak_kv_block_table_bytes: 0,
            peak_kv_blocks_per_node: 0,
            peak_allocated_kv_tokens_per_node: 0,
            peak_kv_fragmentation_tokens_per_node: 0,
            peak_kv_block_table_bytes_per_node: 0,
            peak_kv_blocks_per_gpu: 0,
            peak_allocated_kv_tokens_per_gpu: 0,
            peak_kv_fragmentation_tokens_per_gpu: 0,
            peak_kv_block_table_bytes_per_gpu: 0,
            decode_sequence_utilization: 0.0,
            resident_token_utilization: 0.0,
            kv_block_utilization: 0.0,
            decode_sequence_per_node_utilization: 0.0,
            resident_token_per_node_utilization: 0.0,
            kv_block_per_node_utilization: 0.0,
            decode_sequence_per_gpu_utilization: 0.0,
            resident_token_per_gpu_utilization: 0.0,
            kv_block_per_gpu_utilization: 0.0,
            scheduled_makespan_s: f64::INFINITY,
            scheduled_requests: 0,
            admitted_requests: 0,
            completed_requests: 0,
            rejected_requests: 0,
            timed_out_requests: 0,
            cancelled_requests: 0,
            deadline_constrained_requests: 0,
            deadline_missed_requests: 0,
            measured_requests: 0,
            measurement_start_s: f64::INFINITY,
            measurement_end_s: f64::INFINITY,
        }
    }
}
